Traceback (most recent call last):
  File ".\errExample2.py", line 4, in <module>
    raise Exception('This is an error message.')
Exception: This is an error message.
